### ISSUE TITLE
Database: Users table not created automatically?

### ISSUE THREAD

**Issue by fabiancdng** [iTechnious/BulletFlask#3]
All MySQL tables seem to be created automatically except for the users table.

![Screenshot 2022-01-01 at 15 06 46](https://user-images.githubusercontent.com/36338179/147852401-69dd0bf3-2edd-46b7-8093-fca28bcc1e99.png)

Could you look into that @AuxiliumCDNG?

**Comment by AuxiliumCDNG** [comment]
This is likely because the users table is used by Flask-Login instead of the db helper.
I'll have a look!

Happy new years by the way :)

**Comment by AuxiliumCDNG** [comment]
Should be fixed by 1052292.

**Comment by fabiancdng** [comment]
@AuxiliumCDNG Happy new year 🎉🥳

And yes, it seems to work now, thanks!
